# Generated by Django 4.2.1 on 2023-06-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
