# Generated by Django 4.2.1 on 2023-06-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_request',
            name='name',
            field=models.CharField(default='Default Name', max_length=32),
        ),
    ]
